name: smart_store
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

#  auto_size_text: 3.0.0
#  cached_network_image: 3.3.1
  flutter_animate: 4.1.1+1
#  flutter_barcode_scanner:
#    git:
#      url: https://github.com/FlutterFlow/flutter_barcode_scanner
#  font_awesome_flutter: 10.6.0
#  from_css_color: 2.0.0
#  go_router: 12.1.3
#  google_fonts: 6.1.0
  intl: 0.18.1
#  json_path: 0.6.2
  page_transition: 2.1.0
  path_provider: 2.0.14

  provider: 6.0.5
  shared_preferences: ^2.2.3
#  timeago: 3.2.2
  url_launcher: 6.2.5
#  mobile_scanner: ^5.1.1
  qr_code_scanner: ^1.0.1


  cupertino_icons: ^1.0.2
  dio: ^5.5.0+1
  logger: ^2.0.2+1

  dio_flutter_transformer2:
    git:
      url: https://github.com/mohanadshaban/dio_flutter_transformer.git
  hive: ^2.2.3
  dart_either: ^1.0.0
  flutter_bloc: ^8.1.6
  audioplayers: ^6.0.0
  bot_toast: ^4.1.3



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/audios/


  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  fonts:
   - family: tajwal
     fonts:
       - asset: assets/fonts/tajwal_font.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

