import 'package:flutter/material.dart';

// const lightColorScheme = ColorScheme(
//   brightness: Brightness.light,
//   primary: Color(0xff145794),
//   onPrimary: Colors.white,
//   secondary: Color(0xff90CAF9),
//   onSecondary: Colors.white,
//   error: Colors.redAccent,
//   onError: Colors.white,
//   background: Colors.white,
//   onBackground: Color(0xff13181F),
//   surface: Color(0xff0C66E4),
//   onSurface: Color(0xff13181F),
// );

const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xff145794),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFFEADDFF),
  onPrimaryContainer: Color(0xff002b4f),
  secondary: Color(0xFF3F79FA),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFE8DEF8),
  onSecondaryContainer: Color(0xFF1E2536),
  error: Color(0xFFB3261E),
  onError: Color(0xFFFFFFFF),
  errorContainer: Color(0xFFF9DEDC),
  onErrorContainer: Color(0xFF410E0B),
  background: Color(0xFFFFFBFE),
  onBackground: Color(0xFF1C1B1F),
  surface: Color(0xFFFFFBFE),
  onSurface: Color(0xFF1C1B1F),
  surfaceVariant: Color(0xFFE7E0EC),
  onSurfaceVariant: Color(0xFF49454F),
  outline: Color(0xFF79747E),
  outlineVariant: Color(0xFFCAC4D0),
  shadow: Color(0xFF000000),
  scrim: Color(0xFF000000),
  inverseSurface: Color(0xFF313033),
  onInverseSurface: Color(0xFFF4EFF4),
  inversePrimary: Color(0xFF68CEFD),
  // The surfaceTint color is set to the same color as the primary.
  surfaceTint: Color(0xff145794),
);